r"""Register/unregister the Nyx Suite native messaging host.

Usage:
  python install_host.py --register
  python install_host.py --unregister

Per-OS registration:
  Windows: HKCU\Software\Google\Chrome\NativeMessagingHosts\com.nyxsuite.agent
  macOS:   ~/Library/Application Support/Google/Chrome/NativeMessagingHosts/com.nyxsuite.agent.json
  Linux:   ~/.config/google-chrome/NativeMessagingHosts/com.nyxsuite.agent.json
"""

import argparse
import json
import os
import shutil
import sys
from pathlib import Path

HOST_NAME = "com.nyxsuite.agent"
HOST_DIR = Path(__file__).resolve().parent

# Register the host for every Chromium-family browser, not just Chrome — each one
# reads its OWN location, so a Chrome-only registration shows "native messaging
# host not found" in Edge/Brave/etc.
WIN_BROWSER_KEYS = [
    r"Software\Google\Chrome\NativeMessagingHosts",
    r"Software\Microsoft\Edge\NativeMessagingHosts",
    r"Software\BraveSoftware\Brave-Browser\NativeMessagingHosts",
    r"Software\Chromium\NativeMessagingHosts",
    r"Software\Google\Chrome Beta\NativeMessagingHosts",
    r"Software\Google\Chrome Dev\NativeMessagingHosts",
    r"Software\Vivaldi\NativeMessagingHosts",
]
MAC_SUPPORT_DIRS = [
    "Google/Chrome", "Microsoft Edge", "BraveSoftware/Brave-Browser",
    "Chromium", "Google/Chrome Beta", "Vivaldi",
]
LINUX_CONFIG_DIRS = [
    "google-chrome", "microsoft-edge", "BraveSoftware/Brave-Browser",
    "chromium", "vivaldi",
]
# Always register at least the primary browser even if its profile dir is absent.
PRIMARY_UNIX_DIRS = {"Google/Chrome", "google-chrome"}


def _manifest_path():
    if sys.platform == "win32":
        return HOST_DIR / f"{HOST_NAME}.json"
    elif sys.platform == "darwin":
        return Path.home() / "Library" / "Application Support" / "Google" / "Chrome" / "NativeMessagingHosts" / f"{HOST_NAME}.json"
    elif sys.platform.startswith("linux"):
        for base in [
            Path.home() / ".config" / "google-chrome",
            Path.home() / ".config" / "chromium",
            Path.home() / ".config" / "BraveSoftware" / "Brave-Browser",
        ]:
            nm_dir = base / "NativeMessagingHosts"
            if nm_dir.exists():
                return nm_dir / f"{HOST_NAME}.json"
        return Path.home() / ".config" / "google-chrome" / "NativeMessagingHosts" / f"{HOST_NAME}.json"
    return HOST_DIR / f"{HOST_NAME}.json"


def _resolve_host_runner():
    if getattr(sys, "frozen", False):
        return str(HOST_DIR / "host_main.exe")
    if sys.platform == "win32":
        return str(HOST_DIR / "host_main.bat")
    # macOS/Linux: point Chrome at a /bin/sh wrapper that resolves an absolute
    # Python. Chrome launches the host with a stripped PATH, so a bare
    # `#!/usr/bin/env python3` host script fails ("Native host has exited").
    return str(HOST_DIR / "host_main.sh")


def _macos_host_launcher_path():
    return (
        Path.home() / "Library" / "Application Support" / "NyxSuite"
        / "host" / "nyx_host_launcher.sh"
    )


def _write_macos_host_launcher():
    """Create/refresh the macOS native-host launcher OUTSIDE protected folders.

    macOS TCC denies Chrome permission to *execute* a native-messaging host that
    lives in a protected folder (~/Documents, ~/Desktop, ~/Downloads) — Chrome
    reads the manifest fine (it's in ~/Library) but the spawn is blocked, so the
    host never runs and Chrome reports "Native host has exited". We therefore
    install a tiny /bin/sh launcher under ~/Library/Application Support (never
    TCC-protected) that resolves an absolute Python and exec's the real
    host_main.py inside the install folder — once a process is running it can
    read/exec the project freely; only the file Chrome spawns directly must live
    outside the protected folder.

    Regenerated on every register() so it always points at the install whose
    bridge started last (matches today's single-manifest behaviour).
    """
    import shlex

    project_root = HOST_DIR.parent
    launcher = _macos_host_launcher_path()
    launcher.parent.mkdir(parents=True, exist_ok=True)
    root_q = shlex.quote(str(project_root))
    script = (
        "#!/bin/sh\n"
        "# Generated by install_host.register(). Lives outside ~/Documents so\n"
        "# Chrome on macOS can exec it; drives the real host inside the install\n"
        "# folder. Do not edit — it is regenerated on every bridge start.\n"
        'PATH="/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"\n'
        f"ROOT={root_q}\n"
        'for PY in "$ROOT/.venv/bin/python3" "$ROOT/venv/bin/python3" \\\n'
        '          "$ROOT/.venv/bin/python" "$ROOT/venv/bin/python" \\\n'
        "          /usr/bin/python3 /opt/homebrew/bin/python3 /usr/local/bin/python3 ; do\n"
        '  if [ -x "$PY" ]; then exec "$PY" "$ROOT/agent_host/host_main.py"; fi\n'
        "done\n"
        'exec python3 "$ROOT/agent_host/host_main.py"\n'
    )
    launcher.write_text(script, encoding="utf-8")
    try:
        import stat as _stat

        launcher.chmod(launcher.stat().st_mode | _stat.S_IXUSR | _stat.S_IXGRP | _stat.S_IXOTH)
    except Exception:
        pass
    return launcher


def _write_unix_manifests(base, browser_dirs, updated):
    written = 0
    for d in browser_dirs:
        browser_base = base / d
        nm_dir = browser_base / "NativeMessagingHosts"
        try:
            # Register for browsers that look installed (their profile dir exists),
            # plus always the primary so the host is available immediately.
            if browser_base.exists() or d in PRIMARY_UNIX_DIRS:
                nm_dir.mkdir(parents=True, exist_ok=True)
                (nm_dir / f"{HOST_NAME}.json").write_text(updated, encoding="utf-8")
                written += 1
        except Exception as exc:
            print(f"  skip {d}: {exc}")
    return written


def register():
    manifest = HOST_DIR / f"{HOST_NAME}.json"
    if not manifest.exists():
        print(f"Manifest not found: {manifest}")
        return False

    manifest_data = json.loads(manifest.read_text(encoding="utf-8-sig"))
    if sys.platform == "darwin":
        # macOS TCC blocks Chrome from exec'ing a host inside ~/Documents et al.,
        # so point the manifest at a launcher we install under ~/Library.
        manifest_data["path"] = str(_write_macos_host_launcher())
    else:
        manifest_data["path"] = _resolve_host_runner()
    updated = json.dumps(manifest_data, indent=2)

    if sys.platform == "win32":
        manifest.write_text(updated, encoding="utf-8")
        import winreg
        registered = 0
        for key_path in WIN_BROWSER_KEYS:
            full = f"{key_path}\\{HOST_NAME}"
            try:
                with winreg.CreateKey(winreg.HKEY_CURRENT_USER, full) as key:
                    winreg.SetValueEx(key, "", 0, winreg.REG_SZ, str(manifest))
                registered += 1
            except Exception as exc:
                print(f"  skip {key_path}: {exc}")
        print(f"Registered native messaging host for {registered} browser location(s).")
        return registered > 0

    # The release ZIP (built with Compress-Archive) drops the Unix exec bit, and
    # Chrome needs +x to launch the native host. Restore it whenever we register
    # so the extension's "Connect" works on a fresh macOS/Linux install.
    try:
        import stat as _stat

        runner_path = Path(manifest_data["path"])
        if runner_path.exists():
            mode = runner_path.stat().st_mode
            runner_path.chmod(mode | _stat.S_IXUSR | _stat.S_IXGRP | _stat.S_IXOTH)
    except Exception as exc:
        print(f"  could not mark host runner executable: {exc}")

    base = (Path.home() / "Library" / "Application Support") if sys.platform == "darwin" else (Path.home() / ".config")
    browser_dirs = MAC_SUPPORT_DIRS if sys.platform == "darwin" else LINUX_CONFIG_DIRS
    written = _write_unix_manifests(base, browser_dirs, updated)
    print(f"Registered native messaging host at {written} location(s).")
    return written > 0


def unregister():
    if sys.platform == "win32":
        import winreg
        removed = 0
        for key_path in WIN_BROWSER_KEYS:
            full = f"{key_path}\\{HOST_NAME}"
            try:
                winreg.DeleteKey(winreg.HKEY_CURRENT_USER, full)
                removed += 1
            except FileNotFoundError:
                pass
            except Exception as exc:
                print(f"  skip {key_path}: {exc}")
        print(f"Unregistered native messaging host from {removed} location(s).")
        return True

    base = (Path.home() / "Library" / "Application Support") if sys.platform == "darwin" else (Path.home() / ".config")
    browser_dirs = MAC_SUPPORT_DIRS if sys.platform == "darwin" else LINUX_CONFIG_DIRS
    removed = 0
    for d in browser_dirs:
        target = base / d / "NativeMessagingHosts" / f"{HOST_NAME}.json"
        try:
            if target.exists():
                target.unlink()
                removed += 1
        except Exception as exc:
            print(f"  skip {d}: {exc}")
    print(f"Unregistered native messaging host from {removed} location(s).")
    return True


def main():
    parser = argparse.ArgumentParser(description="Install/uninstall Nyx Suite native messaging host")
    parser.add_argument("--register", action="store_true", help="Register the native messaging host")
    parser.add_argument("--unregister", action="store_true", help="Unregister the native messaging host")
    args = parser.parse_args()

    if args.register:
        return 0 if register() else 1
    elif args.unregister:
        return 0 if unregister() else 1
    else:
        parser.print_help()
        return 1


if __name__ == "__main__":
    sys.exit(main())
